apiVersion: v1
kind: Secret
metadata:
  name: "{{.Values.deploy.botName}}-config"
type: Opaque
data:
  {{ $configPath := printf "%s%s" .Values.deploy.botName "/config.json" }}
  config.json: {{ .Files.Get $configPath | b64enc }}
