apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-data
  namespace: "freqtrade"
  labels:
    app: freqtrade
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
